- name: aplly common configuration to all nodes
  hosts: all
  roles:
    - common
    - smtp
    - httpd

- name: deploy and configure faf
  hosts: faf
  roles:
    - db
    - memcached
    - ansible-faf

- name: deploy and configure retrace server
  hosts: retrace_server
  roles:
    - ansible-retrace-server
