- name: aplly common configuration to all nodes
  hosts: all
  roles:
    - common
    - smtp

- name: deploy and configure PostgreSQL database server
  hosts: db
  roles:
    - db

- name: deploy and configure faf
  hosts: faf
  roles:
    - httpd
    - memcached
    - faf

- name: deploy and configure retrace server
  hosts: retrace_server
  roles:
    - httpd
    - retrace_server
