- name: install PostgreSQL packages
  yum : name={{ item }} state=installed
  with_items:
  - postgresql
  - postgresql-server
  - python-psycopg2
  - pg-semver

- name: stop PostgreSQL
  service: name=postgresql state=stopped
  when: recreate_database

- name: delete PostgreSQL data dir
  file: path=/var/lib/pgsql/data/ state=absent
  when: recreate_database

- name: check /usr/bin/postgresql-setup existence
  stat: path=/usr/bin/postgresql-setup
  register: pgsetup_exists

- name: initialize PostgreSQL database with postgresql-setup
  command: /usr/bin/postgresql-setup initdb
  when: first_time_setup and pgsetup_exists.stat.exists == True

- name: initialize PostgreSQL database
  command: /sbin/service postgresql initdb
  when: first_time_setup and pgsetup_exists.stat.exists == False

- name: start the PostgreSQL service
  service: name=postgresql state=started enabled=yes

- postgresql_db: name=faf
  when: first_time_setup
  sudo: yes
  sudo_user: postgres

- postgresql_user: db=faf name=faf priv=ALL
  when: first_time_setup
  sudo: yes
  sudo_user: postgres

- name: load semver extension
  command: /usr/bin/psql -d faf -c "CREATE EXTENSION semver;"
  when: first_time_setup
  sudo: yes
  sudo_user: postgres
  register: create_ext_result
  ignore_errors: True

- name: load semver extension for PostgreSQL older than 9.1
  command: /usr/bin/psql -d faf -f /usr/share/pgsql/contrib/semver.sql
  when: first_time_setup and create_ext_result|failed
  sudo: yes
  sudo_user: postgres
