- name: install required packages
  yum : name={{ item }} state=installed
  with_items:
  - postfix

- name: configure postfix
  template: src=etc-postfix-main.cf.j2
    dest=/etc/postfix/main.cf
  notify:
  - restart postfix

- name: enable mail services
  service: name={{ item }} enabled=yes
  with_items:
  - postfix
