- name: install pound package
  yum : name={{ item }} state=installed
  with_items:
  - Pound

# Self-Signed
- name: install openssl
  yum : name=openssl state=installed
  when: not (ssl_key_src_path or ssl_cert_src_path)

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/CN={{ domain }}" -days 3650 -keyout "{{ ssl_key_dest_path }}"  -out "{{ ssl_cert_dest_path }}"
  args:
    creates: "{{ ssl_cert_dest_path }}"
  when: not (ssl_key_src_path or ssl_cert_src_path)

# User provided
- name: copy SSL key
  copy: src={{ ssl_key_src_path }} dest={{ ssl_key_dest_path }} mode=640
  when: ssl_key_src_path and ssl_cert_src_path

- name: copy SSL cert
  copy: src={{ ssl_cert_src_path }} dest={{ ssl_cert_dest_path }} mode=644
  when: ssl_key_src_path and ssl_cert_src_path

- name: install certificate and key
  shell: cat "{{ ssl_key_dest_path }}" "{{ ssl_cert_dest_path }}" > "{{ ssl_cert_pem_dest_path }}"
  args:
    creates: "{{ ssl_cert_pem_dest_path }}"
  notify:
  - restart pound

- name: configure pound
  template: src=etc-pound.cfg.j2
    dest=/etc/pound.cfg
  notify:
  - restart pound

- name: enable pound service
  service: name=pound state=started enabled=yes
