- name: install varnish package
  yum : name={{ item }} state=installed
  with_items:
  - varnish

- name: get varnish version
  command: /usr/bin/rpm -q varnish
  register: varnish_ver

- name: add varnish vcl (for varnish < 4.0)
  template: src=etc-varnish-default.vcl.j2
    dest=/etc/varnish/default.vcl
  notify:
  - restart varnish
  when: varnish_ver.stdout.find('varnish-3') != -1

- name: add varnish vcl (for varnish >= 4.0)
  template: src=etc-varnish-default.vcl4.j2
    dest=/etc/varnish/default.vcl
  notify:
  - restart varnish
  when: varnish_ver.stdout.find('varnish-4') != -1

- name: add varnish params
  template: src=etc-varnish-varnish.params.j2
    dest=/etc/varnish/varnish.params
  notify:
  - restart varnish

- name: enable varnish service
  service: name=varnish state=started enabled=yes
