- name: install faf-webui packages
  yum : name={{ item }} state=latest
  with_items:
    - faf-webui
    - faf-webui2

- name: check /etc/faf/faf.conf existence so we don't overwrite it in case there's faf's storage as well
  stat: path=/etc/faf/faf.conf
  register: etcfaf_exists

- name: provide /etc/faf/faf.conf
  template: src=etc-faf.conf.j2
    dest=/etc/faf/faf.conf
  when: etcfaf_exists.stat.exists == False
  notify:
  - restart httpd

- name: put webfaf on root (/) if configured
  template: src=etc-httpd-conf.d-faf-web2.conf.j2
    dest=/etc/httpd/conf.d/faf-web2.conf
  when: webfaf_on_root
  notify:
  - restart httpd
