- name: install memcached package
  yum : name={{ item }} state=installed
  with_items:
  - memcached

- name: install python-pylibmc package for Fedora
  yum : name={{ item }} state=installed
  with_items:
  - python-pylibmc
  when: ansible_distribution == 'Fedora'

- name: install python-memcached package for Epel
  yum : name={{ item }} state=installed
  with_items:
  - python-memcached
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: configure memcached
  template: src=etc-sysconfig-memcached
    dest=/etc/sysconfig/memcached
  notify:
  - restart memcached

- name: start memcached service
  service: name=memcached state=started enabled=yes
