- name: install PostgreSQL packages
  package: name={{ item }} state=installed
  with_items:
  - postgresql
  - postgresql-server
  - python-psycopg2
  - pg-semver
  tags:
  - packages
  - postgresql

- name: stop PostgreSQL
  service: name=postgresql state=stopped
  when: faf_recreate_database is defined and faf_recreate_database
  tags:
  - postgresql

- name: delete PostgreSQL data dir
  file: path=/var/lib/pgsql/data/ state=absent
  when: faf_recreate_database is defined and faf_recreate_database
  tags:
  - postgresql

- name: check postgresql initdb
  stat: path=/var/lib/pgsql/data/postgresql.conf
  register: init_st
  tags:
  - postgresql

- name: initialize PostgreSQL database with postgresql-setup
  command: /usr/bin/postgresql-setup initdb
  when: init_st.stat.exists == false
  tags:
  - postgresql

- name: start the PostgreSQL service
  service: name=postgresql state=started enabled=yes
  tags:
  - postgresql

- name: create faf database
  postgresql_db: name=faf owner=postgres state=present
  become: yes
  become_user: postgres
  tags:
  - postgresql

- postgresql_user: db=faf name=faf priv=ALL role_attr_flags=SUPERUSER state=present
  become: yes
  become_user: postgres
  tags:
  - postgresql

- name: create semver extension
  postgresql_ext: name=semver db=faf state=present
  become: yes
  become_user: postgres
  tags:
  - postgresql
