- name: aplly common configuration to all nodes
  hosts: all
  sudo: yes
  roles:
    - common
    - smtp

- name: deploy and configure PostgreSQL database server
  hosts: db
  sudo: yes
  roles:
    - db

- name: deploy and configure faf
  hosts: faf
  sudo: yes
  roles:
    - httpd
    - memcached
    - faf
