- name: install httpd package
  package: name={{ item }} state=installed
  with_items:
  - httpd
  - mod_ssl
  tags:
  - packages
  - httpd

- name: provide conf.modules.d for EL6
  copy: src=conf.modules.d/
    dest=/etc/httpd/conf.modules.d/
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
  tags:
  - config
  - httpd

- name: configure httpd
  template: src=etc-httpd-conf-httpd.conf.j2
    dest=/etc/httpd/conf/httpd.conf
  notify:
  - restart httpd
  tags:
  - config
  - httpd

- name: copy SSL key
  copy: src={{ ssl_key_src_path }} dest={{ ssl_key_dest_path }} mode=640
  when: ssl_key_src_path and ssl_key_dest_path
  tags:
  - config
  - httpd

- name: copy SSL cert
  copy: src={{ ssl_cert_src_path }} dest={{ ssl_cert_dest_path }} mode=644
  when: ssl_cert_src_path and ssl_cert_dest_path
  tags:
  - config
  - httpd

- name: copy SSL chain cert
  copy: src={{ ssl_cert_chain_src_path }} dest={{ ssl_cert_chain_dest_path }} mode=644
  when: ssl_cert_chain_src_path and ssl_cert_chain_dest_path
  tags:
  - config
  - httpd

- name: add ssl vhost
  template: src=ssl-vhost.conf.j2
    dest=/etc/httpd/conf.d/ssl-vhost.conf
  when: ssl_key_src_path is defined and ssl_key_src_path
  notify:
  - restart httpd
  tags:
  - config
  - httpd

- name: delete default ssl config
  file: path=/etc/httpd/conf.d/ssl.conf
    state=absent
  when: ssl_key_src_path is defined and ssl_key_src_path
  notify:
  - restart httpd
  tags:
  - config
  - httpd

- name: enable httpd service
  service: name=httpd state=started enabled=yes
  tags:
  - config
  - httpd
