- name: set correct hostname
  hostname: name={{ hostname }}

- name: install common packages
  yum : name={{ item }} state=installed
  with_items:
  - iptables
  - libselinux-python
  - ntp
  - policycoreutils
  - policycoreutils-python
  - vim
  - sudo

- name: install common packages for Fedora
  yum : name={{ item }} state=installed
  with_items:
  - bash-completion
  - iptables-services
  when: ansible_distribution == 'Fedora'

- name: make sure we have the right time
  shell: ntpdate -u 0.europe.pool.ntp.org
  ignore_errors: yes

- name: start the ntp service
  service: name=ntpd state=started enabled=yes

#- name: SELinux Enforcing (Targeted)
#  selinux: policy=targeted state=enforcing
#  ignore_errors: yes
#
# No SELinux support yet :(
# ignore_errors required as this fails in LXC
#
- name: SELinux Permissive
  selinux: policy=targeted state=permissive
  ignore_errors: yes

- name: create the EPEL Repository
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: create ABRT Repository for EL
  copy: src=epel-abrt.repo dest=/etc/yum.repos.d/epel-abrt.repo
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6' and custom_faf_repository_url is not defined

- name: create ABRT Repository for Fedora
  copy: src=fedora-abrt.repo dest=/etc/yum.repos.d/fedora-abrt.repo
  when: ansible_distribution == 'Fedora' and custom_faf_repository_url is not defined

- name: remove ABRT repository if custom repo is enabled
  file: path=/etc/yum.repos.d/fedora-abrt.repo
    state=absent
  when: custom_faf_repository_url is defined

- name: create custom FAF repository
  template: src=custom-faf.repo.j2
    dest=/etc/yum.repos.d/custom-faf.repo
  when: custom_faf_repository_url is defined

- name: remove custom repository if present and disabled
  file: path=/etc/yum.repos.d/custom-faf.repo
    state=absent
  when: custom_faf_repository_url is not defined

- name: clean repository metadata for custom repository
  shell: yum --disablerepo=* --enablerepo=faf clean metadata
  when: force_reinstall and custom_faf_repository_url is defined

- name: clean repository metadata for abrt repository
  shell: yum --disablerepo=* --enablerepo=*-abrt clean metadata
  when: force_reinstall and custom_faf_repository_url is not defined

- name: set root alias
  lineinfile: "dest=/etc/aliases line='root: {{ rootmail }}' regexp='^root:' state=present"
  notify:
  - update mail aliases

- name: configure iptables
  template: src=etc-sysconfig-iptables.j2
    dest=/etc/sysconfig/iptables
  notify:
  - restart iptables

- name: configure ip6tables
  template: src=etc-sysconfig-ip6tables.j2
    dest=/etc/sysconfig/ip6tables
  notify:
  - restart ip6tables
