---

- name: check if firewalld is installed
  command: rpm -q firewalld
  register: fw_check
  changed_when: false
  args:
    warn: no

# skip block if firewalld is missing
- block:
  - name: install python-firewall for fedora
    package: name=python-firewall state=present
    when: ansible_distribution == 'Fedora'

  - name: start and enable firewalld
    service: name=firewalld state=started enabled=yes

  - name: allow https service
    firewalld: service=https permanent=yes state=enabled
    notify: restart firewalld

  when: fw_check|succeeded
