---

- name: check if firewalld is installed
  package_facts:
    manager: "auto"

# skip block if firewalld is missing
- block:
  - name: install python3-firewall
    package: name=python3-firewall state=latest

  - name: start and enable firewalld
    service: name=firewalld state=started enabled=yes

  - name: allow https service
    firewalld: service=https permanent=yes state=enabled
    notify: restart firewalld

  when: "'firewalld' in ansible_facts.packages"
