---

- name: check if firewalld is installed
  command: rpm -q firewalld
  register: fw_check
  changed_when: false
  args:
    warn: no

# skip block if firewalld is missing
- block:
  - name: install python-firewall for fedora
    package: name=python-firewall state=latest
    when: ansible_distribution == 'Fedora' and ansible_distribution_version|int <= 27

  - name: install python3-firewall for fedora 28+
    package: name=python3-firewall state=latest
    when: ansible_distribution == 'Fedora' and ansible_distribution_version|int > 27

  - name: start and enable firewalld
    service: name=firewalld state=started enabled=yes

  - name: allow https service
    firewalld: service=https permanent=yes state=enabled
    notify: restart firewalld

  when: fw_check is succeeded
