- name: set correct hostname
  hostname: name={{ hostname }}

- name: install common packages
  yum : name={{ item }} state=installed
  with_items:
  - libselinux-python
  - policycoreutils
  - policycoreutils-python
  - vim
  - sudo
  tags:
  - packages

- name: install common packages for Fedora
  yum : name={{ item }} state=installed
  with_items:
  - bash-completion
  when: ansible_distribution == 'Fedora'
  tags:
  - packages

- name: SELinux Enforcing (Targeted)
  selinux: policy="{{selinux_policy}}" state="{{selinux_state}}"
  when: selinux
  tags:
  - selinux

- name: Allow httpd_can_network_memcache SELinux boolean
  shell: setsebool httpd_can_network_memcache 1
  when: selinux
  tags:
  - selinux

- name: create the EPEL Repository
  yum: name="{{ epel_repo_url }}" state=present
  when: ansible_os_family == 'RedHat'
  tags:
  - config

- name: create the GPG key for EPEL
  rpm_key: key="{{ epel_key_path }}" state=present
  when: ansible_os_family == 'RedHat'
  tags:
  - config

- name: create ABRT Repository for EL
  template: src=epel-abrt.repo.j2 dest=/etc/yum.repos.d/epel-abrt.repo
  when: ansible_os_family == 'RedHat' and faf_custom_repository_url is not defined
  tags:
  - config

- name: create ABRT Repository for Fedora
  copy: src=fedora-abrt.repo dest=/etc/yum.repos.d/fedora-abrt.repo
  when: ansible_distribution == 'Fedora' and faf_custom_repository_url is not defined
  tags:
  - config

- name: remove ABRT repository if custom repo is enabled
  file: path=/etc/yum.repos.d/fedora-abrt.repo
    state=absent
  when: faf_custom_repository_url is defined
  tags:
  - config

- name: create custom FAF repository
  template: src=custom-faf.repo.j2
    dest=/etc/yum.repos.d/custom-faf.repo
  when: faf_custom_repository_url is defined
  tags:
  - config

- name: remove custom repository if present and disabled
  file: path=/etc/yum.repos.d/custom-faf.repo
    state=absent
  when: faf_custom_repository_url is not defined
  tags:
  - config

- name: clean repository metadata for custom repository
  shell: yum --disablerepo=* --enablerepo=faf clean metadata
  when: faf_force_reinstall is defined and faf_force_reinstall and faf_custom_repository_url is defined
  ignore_errors: yes

- name: clean repository metadata for abrt repository
  shell: yum --disablerepo=* --enablerepo=*-abrt clean metadata
  when: faf_force_reinstall is defined and faf_force_reinstall and faf_custom_repository_url is not defined
  ignore_errors: yes

- name: set root alias
  lineinfile: "dest=/etc/aliases line='root: {{ rootmail }}' regexp='^root:' state=present"
  notify:
  - update mail aliases
  tags:
  - config

- name: firewalld
  include: firewall.yml
