- name: erase faf packages
  yum: pkg="faf-*" state=absent
  when: force_reinstall
  tags:
  - packages
  - faf

- name: install core faf packages
  yum: pkg={{ item }} state=installed
  with_items: "{{ faf_packages }}"
  tags:
  - packages
  - faf

- name: install faf problem packages
  yum: pkg={{ item }} state=installed
  with_items: "{{ faf_problem_packages }}"
  tags:
  - packages
  - faf

- name: install faf opsys packages
  yum: pkg={{ item }} state=installed
  with_items: "{{ faf_opsys_packages }}"
  tags:
  - packages
  - faf

- name: install faf action packages
  yum: pkg={{ item }} state=installed
  with_items: "{{ faf_action_packages }}"
  tags:
  - packages
  - faf

- name: install faf bugtracker packages
  yum: pkg={{ item }} state=installed
  with_items: "{{ faf_bugtracker_packages }}"
  tags:
  - packages
  - faf
  when: with_bugtrackers

- name: install faf celery packages
  yum: pkg={{ item }} state=installed
  with_items: "{{ faf_celery_packages }}"
  tags:
  - packages
  - faf
  when: with_celery

- name: install faf fedmsg packages
  yum: pkg={{ item }} state=installed
  with_items: "{{ faf_fedmsg_packages }}"
  tags:
  - packages
  - faf
  when: with_fedmsg

- name: install faf solutionfinder packages
  yum: pkg={{ item }} state=installed
  with_items: "{{ faf_solutionfinder_packages }}"
  tags:
  - packages
  - faf
  when: with_solutionfinders

- name: provide /etc/faf/faf.conf
  template: src=etc-faf-faf.conf.j2
    dest=/etc/faf/faf.conf
  tags:
  - config
  - faf

- name: create faf's database schema
  command: faf-migrate-db --create-all
  sudo: yes
  sudo_user: faf
  when: first_time_setup
  tags:
  - config
  - faf

- name: stamp database as migrated to latest version
  command: faf-migrate-db --stamp-only
  sudo: yes
  sudo_user: faf
  when: first_time_setup
  tags:
  - config
  - faf

- name: init faf
  command: faf init
  sudo: yes
  sudo_user: faf
  when: first_time_setup
  tags:
  - config
  - faf

- name: run database migrations
  command: faf-migrate-db
  sudo: yes
  sudo_user: faf
  when: migrate_db
  tags:
  - config
  - faf
