- name: install faf-webui packages
  yum : name={{ item }} state=latest
  with_items: "{{ faf_web_packages }}"
  tags:
  - packages
  - faf

- include: celery.yml
  when: with_celery

- name: install faf web symboltransfer packages
  yum: pkg={{ item }} state=installed
  with_items: "{{ faf_web_symboltransfer_packages }}"
  tags:
  - packages
  - faf
  when: with_symboltransfer

- name: check /etc/faf/faf.conf existence so we don't overwrite it in case there's faf's storage as well
  stat: path=/etc/faf/faf.conf
  register: etcfaf_exists
  tags:
  - config
  - faf

- name: provide /etc/faf/faf.conf
  template: src=etc-faf-faf.conf.j2
    dest=/etc/faf/faf.conf
  when: etcfaf_exists.stat.exists == False
  notify:
  - restart httpd
  tags:
  - config
  - faf

- name: provide /etc/faf/plugins/web2.conf
  template: src=etc-faf-plugins-web2.conf.j2
    dest=/etc/faf/plugins/web2.conf
  notify:
  - restart httpd
  tags:
  - config
  - faf

- name: put webfaf on root (/) if configured
  template: src=etc-httpd-conf.d-faf-web2.conf.j2
    dest=/etc/httpd/conf.d/faf-web2.conf
  when: webfaf_on_root
  notify:
  - restart httpd
  tags:
  - config
  - faf
