- name: install memcached package
  package: name=memcached state=latest
  tags:
  - packages
  - memcached

- name: install python-pylibmc package for Fedora
  package: name=python3-pylibmc state=latest
  when: ansible_distribution == 'Fedora'
  tags:
  - packages
  - memcached

- name: install python-memcached package for EL
  package: name=python-memcached state=latest
  when: ansible_distribution == 'RedHat'
  tags:
  - packages
  - memcached

- name: configure memcached
  template: src=etc-sysconfig-memcached
    dest=/etc/sysconfig/memcached
  notify:
  - restart memcached
  tags:
  - config
  - memcached

- name: enable memcached service
  service: name=memcached state=started enabled=yes
